### ISSUE TITLE
Is it working with latest @adonisjs/lucid v18.3.0?

### ISSUE THREAD

**Issue by rodrigorz** [lookinlab/adonis-lucid-filter#38]
I am using adonis-lucid-filter v4.1.0 and when a try to:
```ts
User.filter(filterData).paginate(page, 10);
```

i am getting this error:
```
{
    "message": "Cannot read properties of undefined (reading 'paginate')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'paginate')\n    at UsersController.index (/home/node/app/app/Controllers/Http/Admin/UsersController.ts:22:26)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at Object.PreCompiler.runRouteHandler [as fn] (/home/node/app/node_modules/@adonisjs/http-server/build/src/Server/PreCompiler/index.js:47:31)\n    at AuthMiddleware.handle (/home/node/app/app/Middleware/Auth.ts:76:5)\n    at Server.handleRequest (/home/node/app/node_modules/@adonisjs/http-server/build/src/Server/index.js:108:13)"
}
```

User Model is extending from `compose(BaseModel, Filterable)` and have the `public static $filter = () => UserFilter`

`User.query().paginate(page, 10)` works.

**Comment by rodrigorz** [comment]
I uninstalled and removed the `adonis-lucid-filter` settings, redid all the configuration and it worked.

Closing this issue. :)
